version: '3.6'

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017

  api:
    build:
      context: $PWD/packages/api
      dockerfile: Dockerfile.dev
    ports:
      - 9230:9230
      - 4000:4000
    volumes:
      - $PWD/packages/api/src:/app/src
    depends_on:
      - mongo

  director:
    build:
      context: $PWD/packages/director
      dockerfile: Dockerfile.dev
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      S3_BUCKET: sorry-cypress
    ports:
      - 9229:9229
      - 1234:1234
    volumes:
      - $PWD/packages/director/src:/app/src
      - $PWD/packages/director/config:/app/config
    depends_on:
      - mongo
