version: '3.6'

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017

  director:
    build: $PWD/packages/director
    environment:
      PORT: 1234
    ports:
      - 9229:9229
      - 1234:1234
    volumes:
      - $PWD/packages/director/src:/app/src
      - $PWD/packages/director/config:/app/config
    depends_on:
      - mongo
