{{- if .Values.registry_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry_secret | b64enc | quote }}
{{- end }}
