# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: master
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
